import './globals.css'
import styles from './layout.module.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
    
      <div style={{
        flex:1,
        width:"100%"
      }}>
        <header className={styles.containerHeader}>
          SIEM
        </header>
      {children}
      </div>
        </body>
    </html>
  )
}
