version: '3.8'
services:
    syslog:
        build: ./syslog
        container_name: tcc-syslog
        ports:
            - 500:514/udp
        networks:
            - app
        links:
            - backend
    backend:
        build: ./backend
        container_name: tcc-backend
        volumes:
            - ./backend:/backend
        ports:
            - 5005:3000
        environment:
            - PORT=3000
            - POSTGRES_HOST=$BACKEND_POSTGRES_HOST
            - POSTGRES_PORT=$BACKEND_POSTGRES_PORT
            - POSTGRES_USER=$BACKEND_POSTGRES_USER
            - POSTGRES_PASSWORD=$BACKEND_POSTGRES_PASSWORD
            - POSTGRES_DB=$BACKEND_POSTGRES_DB
        links:
            - elasticsearch
        env_file: 
            - .env  
        networks:
            - app
        # logging:
        #     driver: syslog
        #     options:
        #         syslog-address: "udp://192.168.0.111:500"
        #         tag: "BACKEND"
    frontend:
        build: ./frontend
        container_name: tcc-frontend
        volumes:
            - ./frontend:/frontend
        environment:
            - NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL
        ports:
            - 3002:3000
        env_file: 
            - .env  
        networks:
            - app
        depends_on:
            - syslog
        logging:
            driver: syslog
            options:
                syslog-address: "udp://192.168.0.111:500"
                tag: "FRONTEND"
    log-database:
        image: postgres
        container_name: tcc-database
        environment:
            - POSTGRES_USER=adm
            - POSTGRES_PASSWORD=12345
            - POSTGRES_DB=logs       
        networks:
            - app
        ports:
            - '5556:5432'
        command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false

            - xpack.security.enrollment.enabled=false
        networks:
            - app

networks:
  app:
    driver: bridge