version: '3.8'
services:
    syslog:
        build: ./syslog
        container_name: tcc-syslog
        ports:
            - 500:514/udp
        links:
            - backend
    backend:
        build: ./backend
        container_name: tcc-backend
        volumes:
            - ./backend:/backend
        ports:
            - 5005:3333
        links:
            - mongo
    frontend:
        build: ./frontend
        container_name: tcc-frontend
        volumes:
            - ./frontend:/frontend
        ports:
            - 3001:5173
        links:
            - backend
    mongo:
        image: mongo
        container_name: tcc-mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
        ports:
            - 3000:27017