version: '3.8'
services:
    syslog:
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - 500:514/udp
        links:
            - backend
    backend:
        build: ./backend
        volumes:
            - /backend
        ports:
            - 5005:3333
    postgres:
        image: postgres
        container_name: tcc-database
        restart: always
        ports:
            - 5100:5432
        links:
            - syslog
        logging:
            driver: syslog
            options:
                syslog-address: "udp://10.0.0.115:500"
        environment:
            POSTGRES_PASSWORD: example