version: '3.8'
services:

    syslog:
        build: ./syslog
        container_name: tcc-syslog
        ports:
            - 500:514/udp
        links:
            - backend
    backend:
        build: ./backend
        container_name: tcc-backend
        volumes:
            - ./backend:/backend
        ports:
            - 5005:${BACKEND_PORT}
        environment:
            - PORT=$BACKEND_PORT
            - POSTGRES_HOST=$BACKEND_POSTGRES_HOST
            - POSTGRES_PORT=$BACKEND_POSTGRES_PORT
            - POSTGRES_USER=$BACKEND_POSTGRES_USER
            - POSTGRES_PASSWORD=$BACKEND_POSTGRES_PASSWORD
            - POSTGRES_DB=$BACKEND_POSTGRES_DB
        links:
            - log-database
        env_file: 
            - .env
    frontend:
        build: ./frontend
        container_name: tcc-frontend
        volumes:
            - ./frontend:/frontend
        environment:
            - NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL
        ports:
            - 3002:3000
        links:
            - backend
        env_file: 
            - .env
    log-database:
        image: postgres
        container_name: tcc-mongo
        environment:
            - POSTGRES_USER=adm
            - POSTGRES_PASSWORD=12345
            - POSTGRES_DB=logs
        ports:
            - '5556:5432'