version: '3.8'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
        container_name: tcc-elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - xpack.security.enrollment.enabled=false
        networks:
            - app
    syslog:
        build: ./syslog
        container_name: tcc-syslog
        ports:
            - 514:514/udp
        networks:
            - app
        links:
            - backend
        depends_on:
            - backend
    backend:
        build: ./backend
        container_name: tcc-backend
        volumes:
            - ./backend:/backend
        environment:
            - PORT=3000
            - POSTGRES_HOST=tcc-database
            - POSTGRES_PORT=5432
            - POSTGRES_USER=adm
            - POSTGRES_PASSWORD=12345
            - POSTGRES_DB=$BACKEND_POSTGRES_DB
            - ELASTIC_SEARCH_URL=http://tcc-elasticsearch:9200
        depends_on:
            - elasticsearch
            - log-database
        env_file: 
            - .env  
        networks:
            - app
    reverse-proxy:
        build: ./nginx
        networks:
            - app
        ports:
            - 3000:80
        depends_on:
            - backend
            - log-database
            - frontend
    frontend:
        build: ./frontend
        container_name: tcc-frontend
        volumes:
            - ./frontend:/frontend
        environment:
            - NEXT_PUBLIC_URL=api-backend
        env_file: 
            - .env  
        networks:
            - app
        depends_on:
            - syslog
        logging:
            driver: syslog
            options:
                syslog-address: "udp://192.168.0.111:500"
                tag: "FRONTEND"
    log-database:
        image: postgres
        container_name: tcc-database
        environment:
            - POSTGRES_USER=adm
            - POSTGRES_PASSWORD=12345
            - POSTGRES_DB=logs       
        networks:
            - app
        ports:
            - '5556:5432'
        command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    

networks:
  app:
    driver: bridge