FROM ubuntu:22.04
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y python3.11
RUN apt-get install -y python3-pip
RUN python3 -m pip install pySigma==0.11.3
RUN python3 -m pip install  sigma-cli

RUN sigma plugin install elasticsearch
RUN  apt-get -y install curl
RUN curl -fsSL https://deb.nodesource.com/setup_18.x -o /tmp/nodesource_setup.sh
RUN bash /tmp/nodesource_setup.sh
RUN apt-get update
RUN apt-get install -y nodejs
RUN apt-get install -y build-essential
RUN npm install --global yarn

WORKDIR /backend
COPY package.json ./

RUN yarn
EXPOSE 3000
COPY . .

CMD [ "yarn", "dev"]
