FROM ubuntu:latest
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN pip install pysigma
RUN python3 -m pip install "sigma-cli==0.7.10"

RUN sigma plugin install elasticsearch

RUN  apt-get -y install curl
RUN curl -fsSL https://deb.nodesource.com/setup_18.x -o /tmp/nodesource_setup.sh
RUN bash /tmp/nodesource_setup.sh
RUN apt-get update
RUN apt-get install -y nodejs
RUN apt-get install -y build-essential
RUN npm install --global yarn

WORKDIR /backend
COPY package.json ./

RUN yarn
EXPOSE 3000
COPY . .

CMD [ "yarn", "dev"]
