FROM ubuntu:latest
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y build-essential
run apt-get install -y wget
RUN  apt-get install -y nano
RUN wget -qO - https://ose-repo.syslog-ng.com/apt/syslog-ng-ose-pub.asc
# RUN apt-key add -
RUN echo "deb https://ose-repo.syslog-ng.com/apt/ stable ubuntu-focal" 
RUN tee -a /etc/apt/sources.list.d/syslog-ng-ose.list

RUN apt-get -y update
RUN apt-get install -y syslog-ng
COPY ./config/syslog-ng.conf /etc/syslog-ng/

CMD ["syslog-ng", "-F"]

expose 514/udp